version: '3'

services:
  
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: "mariadb:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root12345
      MYSQL_DATABASE: food_delivery
    ports:
      - "3308:3306"
    volumes:
      - db:/data/db:rw

  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  express:
    build:
      context: .
      dockerfile: Dockerfile-express
    ports:
      - 8080:8080
    volumes:
      - ./express:/code:rw
volumes:
  db: